version: '3'

services:
  web:
    image: nginx:1.19.1
    ports:
      - '8888:80'
    volumes:
      - ./web_server/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    links:
      - php

  php:
    build:
      context: ./src
    volumes:
      - ./src:/var/www/html
    links:
      - db

  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
